### ISSUE TITLE
create v1.0.0 tag 

### ISSUE THREAD

**Issue by robstoll** [vlsi/github-actions-random-matrix#1]
I would like to use matrix_builder.js and fetch it via git by a specific tag. Would you mind to create a tag (e.g. v1.0.0)?

**Comment by vlsi** [comment]
Added v1.0.0: https://github.com/vlsi/github-actions-random-matrix/tree/v1.0.0

However, I guess it might be easier to clone the js into the target repository since you will need to have a customized generator anyway.

**Comment by robstoll** [comment]
thanks. I don't expect that I will modify maxtrix_builder.js but only the file where I customize the generator. 
And I hope you will create further tags in case you create bug fixes or new features, this way I will be notified automatically via `gt`
