### ISSUE TITLE
how about we provide pre-defined axes?

### ISSUE THREAD

**Issue by robstoll** [vlsi/github-actions-random-matrix#3]
instead of redefining the axes in each project including things like `matrix.imply` etc. it could make sense to provide axes such as java_version/java_distribution in this repo which one can transform if required. each time there is a new java version we could add it to the axes and release a new version of this repo (create a new tag) and others could fetch matrix.js via [gt](https://github.com/tegonal/gt) and then a gt-update-workflow makes sure the repo stays up-to-date. WDYT?

**Comment by vlsi** [comment]
Frankly, I would love to deduplicate it, however, there are challenges:
* Different project support different Java versions. For instance, some projects sill support Java 8 while the others need 11+. It might be solvable by "common" axis producing every Java version while the consumers could add constraints.
* Java version, distribution, architecture are tied to the GitHub CI configuration there are multiple `setup-java` actions, and they have slightly different inputs
* Java EA is supplied in `oracle/setup-java` which gets extra complicated for the setup: https://github.com/apache/jmeter/blob/09c3f810dda7efaf1510ac062454d978d90a0741/.github/workflows/main.yml#L49-L63

This is all solvable, however, I just did not have time to factor it out.
It is annoying indeed to have "the same" imply/... configurations.

----

> via [gt](https://github.com/tegonal/gt) and then a gt-update-workflow makes sure the repo stays up-to-date

An alternative option could be creating an action that would contain `matrix.js`. Then Renovate and Dependabot could suggest PRs with version updates.

**Comment by vlsi** [comment]
Frankly, I would love to deduplicate it, however, there are challenges:
* Different project support different Java versions. For instance, some projects sill support Java 8 while the others need 11+. It might be solvable by "common" axis producing every Java version while the consumers could add constraints.
* Java version, distribution, architecture are tied to the GitHub CI configuration there are multiple `setup-java` actions, and they have slightly different inputs
* Java EA is supplied in `oracle/setup-java` which gets extra complicated for the setup: https://github.com/apache/jmeter/blob/09c3f810dda7efaf1510ac062454d978d90a0741/.github/workflows/main.yml#L49-L63

This is all solvable, however, I just did not have time to factor it out.
It is annoying indeed to have "the same" imply/... configurations.

----

> via [gt](https://github.com/tegonal/gt) and then a gt-update-workflow makes sure the repo stays up-to-date

An alternative option could be creating an action that would contain `matrix.js`. Then Renovate and Dependabot could suggest PRs with version updates.

**Comment by robstoll** [comment]
I expect as well that there will be a lot of differences between projects. I figured that we could come up with a decent default set, which applies to most projects. Something like os=[ubuntu, windows, mac], java_versions = LTS versions + newest etc. but realise now that already this decision is not that obvious, others might want to include all newer java versions since last LTS etc.
I'll start to factor out common settings for the projects I maintain and will see if there are things which could be useful for others

**Comment by vlsi** [comment]
There should probably be "build jdk" and "test jdk" separation. In other words, the project should probably use a fixed JDK for the build purposes (e.g. build with Java 17 and `--target 8`), and use multiple Java versions for testing purposes (e.g. 8, 11, 17, 21)
